#!/usr/bin/env bash

######################
## Prompt Functions ##
######################

# Colors
red() {
  echo "\[\e[0;31m\]"
}

redBold() {
  echo "\[\e[1;31m\]"
}

green() {
  echo "\[\e[0;32m\]"
}

greenBold() {
  echo "\[\e[1;32m\]"
}

blue() {
  echo "\[\e[0;34m\]"
}

blueBold() {
  echo "\[\e[1;34m\]"
}

purple() {
  echo "\[\e[0;35m\]"
}

purpleBold() {
  echo "\[\e[1;35m\]"
}

white() {
  echo "\[\e[0;37m\]"
}

whiteBold() {
  echo "\[\e[1;37m\]"
}

colorDone() {
  echo "\[\033[00m\]"
}

# Shows what branch you're on if in a git repo
gitBranch() {
  local ref=$(git branch 2>/dev/null | sed -n '/\* /s///p')
  if [[ "$ref" != "" ]]
  then
    echo "($ref) "
  fi
}

getHost() {
  if [[ `whoami` = root ]]; then
    echo "$(redBold)#root $(green)$HOSTNAME"
  else
    echo "$(green)$HOSTNAME"
  fi
}


# Prompt string, used in bash_profile
prompt() {
 # The escaped $ prior to gitBranch means that gitBranch is called on each prompt redraw
 echo "`getHost` $(blueBold)\w $(redBold)\$(gitBranch)$(whiteBold)> $(colorDone) "
}
