#!/usr/bin/env bash
# Source all dotfiles
for file in `find ~/.dotfiles/common/`; do
    [[ -f "$file" ]] && source "$file"
done

for file in `find ~/.dotfiles/$(uname -s)/`; do
	[[ -f "$file" ]] && source "$file"
done	

# Add $HOME/bin to path
PATH="$HOME/bin:$PATH"

theme.sh mona-lisa
PS1=$(prompt)  # prompt func from `common/functions`
# Fire up tmux
[[ $- != *i* ]] && return
[[ -z "$TMUX" && -z "$SSH_CLIENT" ]] && exec tmux -f ~/.config/.tmux.conf

