#!/usr/bin/env bash
# Source all dotfiles
for file in `find ~/.dotfiles/common/`; do
    [[ -f "$file" ]] && source "$file"
done

for file in `find ~/.dotfiles/$(uname -s)/`; do
	[[ -f "$file" ]] && source "$file"
done	

# Second condition checks if shell is interactive
# If it's missing, then scp fails with all sorts of nonsense.
if type screenfetch >/dev/null 2>&1 && [[ $- == *i* ]]; then
  screenfetch
fi

PS1=$(prompt)
