#!/usr/bin/env bash
# Source all dotfiles
for file in `find ~/.dotfiles/common/`; do
    [[ -f "$file" ]] && source "$file"
done

for file in `find ~/.dotfiles/$(uname -s)/`; do
	[[ -f "$file" ]] && source "$file"
done	


if type screenfetch >/dev/null 2>&1; then
  screenfetch
fi
